services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  dashboard:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "18081:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: mysql_container
      MYSQL_DB: app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  flask_app:
    build: .
    container_name: flask_container
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql_container
      MYSQL_DB: app-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data: